# Part of the death compass project
# Made by: mision_thi
# Generated by my Excel workbook

execute as @s at @s if score @s dc_d_rot matches 0 run function death_compass:dc_math/compass_point/3
execute as @s at @s if score @s dc_d_rot matches 1 run function death_compass:dc_math/compass_point/4
execute as @s at @s if score @s dc_d_rot matches 2 run function death_compass:dc_math/compass_point/5
execute as @s at @s if score @s dc_d_rot matches 3 run function death_compass:dc_math/compass_point/6
execute as @s at @s if score @s dc_d_rot matches 4 run function death_compass:dc_math/compass_point/7
execute as @s at @s if score @s dc_d_rot matches 5 run function death_compass:dc_math/compass_point/8
execute as @s at @s if score @s dc_d_rot matches 6 run function death_compass:dc_math/compass_point/9
execute as @s at @s if score @s dc_d_rot matches 7 run function death_compass:dc_math/compass_point/10
execute as @s at @s if score @s dc_d_rot matches 8 run function death_compass:dc_math/compass_point/11
execute as @s at @s if score @s dc_d_rot matches 9 run function death_compass:dc_math/compass_point/12
execute as @s at @s if score @s dc_d_rot matches 10 run function death_compass:dc_math/compass_point/13
execute as @s at @s if score @s dc_d_rot matches 11 run function death_compass:dc_math/compass_point/14
execute as @s at @s if score @s dc_d_rot matches 12 run function death_compass:dc_math/compass_point/15
execute as @s at @s if score @s dc_d_rot matches 13 run function death_compass:dc_math/compass_point/16
execute as @s at @s if score @s dc_d_rot matches 14 run function death_compass:dc_math/compass_point/17
execute as @s at @s if score @s dc_d_rot matches 15 run function death_compass:dc_math/compass_point/18
execute as @s at @s if score @s dc_d_rot matches 16 run function death_compass:dc_math/compass_point/19
execute as @s at @s if score @s dc_d_rot matches 17 run function death_compass:dc_math/compass_point/20
execute as @s at @s if score @s dc_d_rot matches 18 run function death_compass:dc_math/compass_point/21
execute as @s at @s if score @s dc_d_rot matches 19 run function death_compass:dc_math/compass_point/22
execute as @s at @s if score @s dc_d_rot matches 20 run function death_compass:dc_math/compass_point/23
execute as @s at @s if score @s dc_d_rot matches 21 run function death_compass:dc_math/compass_point/24
execute as @s at @s if score @s dc_d_rot matches 22 run function death_compass:dc_math/compass_point/25
execute as @s at @s if score @s dc_d_rot matches 23 run function death_compass:dc_math/compass_point/26
execute as @s at @s if score @s dc_d_rot matches 24 run function death_compass:dc_math/compass_point/27
execute as @s at @s if score @s dc_d_rot matches 25 run function death_compass:dc_math/compass_point/28
execute as @s at @s if score @s dc_d_rot matches 26 run function death_compass:dc_math/compass_point/29
execute as @s at @s if score @s dc_d_rot matches 27 run function death_compass:dc_math/compass_point/30
execute as @s at @s if score @s dc_d_rot matches 28 run function death_compass:dc_math/compass_point/31
execute as @s at @s if score @s dc_d_rot matches 29 run function death_compass:dc_math/compass_point/0
execute as @s at @s if score @s dc_d_rot matches 30 run function death_compass:dc_math/compass_point/1
execute as @s at @s if score @s dc_d_rot matches 31 run function death_compass:dc_math/compass_point/2
