# Part of the death compass project
# Made by: mision_thi
# Generated by my Excel workbook

execute as @s at @s if score @s dc_p_rot matches 0 run function death_compass:dc_math/compass_check/0-7/0
execute as @s at @s if score @s dc_p_rot matches 1 run function death_compass:dc_math/compass_check/0-7/1
execute as @s at @s if score @s dc_p_rot matches 2 run function death_compass:dc_math/compass_check/0-7/2
execute as @s at @s if score @s dc_p_rot matches 3 run function death_compass:dc_math/compass_check/0-7/3
execute as @s at @s if score @s dc_p_rot matches 4 run function death_compass:dc_math/compass_check/0-7/4
execute as @s at @s if score @s dc_p_rot matches 5 run function death_compass:dc_math/compass_check/0-7/5
execute as @s at @s if score @s dc_p_rot matches 6 run function death_compass:dc_math/compass_check/0-7/6
execute as @s at @s if score @s dc_p_rot matches 7 run function death_compass:dc_math/compass_check/0-7/7
