# Part of the death compass project
# Made by: mision_thi
# Generated by my Excel workbook

execute as @s at @s if score @s dc_p_rot matches 16 run function death_compass:dc_math/compass_check/16-23/16
execute as @s at @s if score @s dc_p_rot matches 17 run function death_compass:dc_math/compass_check/16-23/17
execute as @s at @s if score @s dc_p_rot matches 18 run function death_compass:dc_math/compass_check/16-23/18
execute as @s at @s if score @s dc_p_rot matches 19 run function death_compass:dc_math/compass_check/16-23/19
execute as @s at @s if score @s dc_p_rot matches 20 run function death_compass:dc_math/compass_check/16-23/20
execute as @s at @s if score @s dc_p_rot matches 21 run function death_compass:dc_math/compass_check/16-23/21
execute as @s at @s if score @s dc_p_rot matches 22 run function death_compass:dc_math/compass_check/16-23/22
execute as @s at @s if score @s dc_p_rot matches 23 run function death_compass:dc_math/compass_check/16-23/23
