# Part of the death compass project
# Made by: mision_thi
# Generated by my Excel workbook

execute as @s at @s if score @s dc_p_rot matches 24 run function death_compass:dc_math/compass_check/24-31/24
execute as @s at @s if score @s dc_p_rot matches 25 run function death_compass:dc_math/compass_check/24-31/25
execute as @s at @s if score @s dc_p_rot matches 26 run function death_compass:dc_math/compass_check/24-31/26
execute as @s at @s if score @s dc_p_rot matches 27 run function death_compass:dc_math/compass_check/24-31/27
execute as @s at @s if score @s dc_p_rot matches 28 run function death_compass:dc_math/compass_check/24-31/28
execute as @s at @s if score @s dc_p_rot matches 29 run function death_compass:dc_math/compass_check/24-31/29
execute as @s at @s if score @s dc_p_rot matches 30 run function death_compass:dc_math/compass_check/24-31/30
execute as @s at @s if score @s dc_p_rot matches 31 run function death_compass:dc_math/compass_check/24-31/31
