# Part of the death compass project
# Made by: mision_thi
# Generated by my Excel workbook

execute as @s at @s if score @s dc_p_rot matches 8 run function death_compass:dc_math/compass_check/8-15/8
execute as @s at @s if score @s dc_p_rot matches 9 run function death_compass:dc_math/compass_check/8-15/9
execute as @s at @s if score @s dc_p_rot matches 10 run function death_compass:dc_math/compass_check/8-15/10
execute as @s at @s if score @s dc_p_rot matches 11 run function death_compass:dc_math/compass_check/8-15/11
execute as @s at @s if score @s dc_p_rot matches 12 run function death_compass:dc_math/compass_check/8-15/12
execute as @s at @s if score @s dc_p_rot matches 13 run function death_compass:dc_math/compass_check/8-15/13
execute as @s at @s if score @s dc_p_rot matches 14 run function death_compass:dc_math/compass_check/8-15/14
execute as @s at @s if score @s dc_p_rot matches 15 run function death_compass:dc_math/compass_check/8-15/15
